[Interface]
Address = 10.13.13.2
PrivateKey = sPWd/qpp7IayJSG7yG3Cgbj3cD8eTPhYsmiYO3rAo3k=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = 4MtyWRjg76NrX+7WCdOYnaULfwwDierOWY1Bhj4j1g4=
PresharedKey = WDXZ5LvUiDSG3CRaVNxZj3LqmnhrUxUMp+iDjXBREbM=
Endpoint = 192.168.1.38:51820
AllowedIPs = 0.0.0.0/0
